export function stableStringify(value) {
  if (value === null || typeof value !== 'object') return JSON.stringify(value);
  if (Array.isArray(value)) return '[' + value.map(stableStringify).join(',') + ']';
  return '{' + Object.keys(value).sort().map((key) => JSON.stringify(key) + ':' + stableStringify(value[key])).join(',') + '}';
}

export function buildModelSignature(state, kind = 'projection') {
  const base = {
    kind,
    dob: state.dob,
    currentAge: state.currentAge,
    valuationDate: state.valuationDate,
    firstYearMonths: state.firstYearMonths,
    retireAge: state.retireAge,
    earlyAge: state.earlyAge,
    stateAge: state.stateAge,
    endAge: state.endAge,
    pot: state.pot,
    salary: state.salary,
    salaryGrowth: state.salaryGrowth,
    empPct: state.empPct,
    erPct: state.erPct,
    returnNom: state.returnNom,
    inflation: state.inflation,
    vol: state.vol,
    drawdown: state.drawdown,
    feePct: state.feePct,
    statePension: state.statePension,
    otherIncome: state.otherIncome,
    allowance: state.allowance,
    basicTax: state.basicTax,
    higherTax: state.higherTax,
    higherThreshold: state.higherThreshold,
    tflsPct: state.tflsPct,
    tflsCap: state.tflsCap,
    crashPct: state.crashPct,
    badYears: state.badYears,
    badPenalty: state.badPenalty,
    successAge: state.successAge,
    floor70: state.floor70,
    bridgeMode: state.bridgeMode,
    bridgeAmount: state.bridgeAmount,
    bridgeEndAge: state.bridgeEndAge,
    bridgePostDraw: state.bridgePostDraw,
    bridgeKeepLifestyle: state.bridgeKeepLifestyle,
    bridgeCrashEarly: state.bridgeCrashEarly,
    bridgeCrashState: state.bridgeCrashState,
    bridgeBadSeq: state.bridgeBadSeq,
    householdMode: state.householdMode,
    spouseDob: state.spouseDob,
    spouseValuationDate: state.spouseValuationDate,
    spouseCurrentAge: state.spouseCurrentAge,
    spouseFirstYearMonths: state.spouseFirstYearMonths,
    spouseRetireAge: state.spouseRetireAge,
    spouseStateAge: state.spouseStateAge,
    spousePot: state.spousePot,
    spouseSalary: state.spouseSalary,
    spouseEmpPct: state.spouseEmpPct,
    spouseErPct: state.spouseErPct,
    spouseStatePension: state.spouseStatePension,
    spouseOtherIncome: state.spouseOtherIncome,
    dcPensions: state.dcPensions || [],
    dbPensions: state.dbPensions || [],
    contribEvents: state.contribEvents || [],
    lumpSumEvents: state.lumpSumEvents || [],
    partnerDcPensions: state.partnerDcPensions || [],
    partnerDbPensions: state.partnerDbPensions || [],
    partnerContribEvents: state.partnerContribEvents || [],
    partnerLumpSumEvents: state.partnerLumpSumEvents || [],
    sims: state.sims,
    seed: state.seed,
    ruinDef: state.ruinDef,
    bands: state.bands,
  };
  return stableStringify(base);
}
